<?php
$cardIds = [
  // Empire
  'EmpireAragon',
  'EmpireByzantium',
  'EmpireEngland',
  'EmpireFrance',
  'EmpireHolyRomanEmpire',
  'EmpireHungary',
  'EmpireMamluk',
  'EmpireOttoman',
  'EmpirePapalStates',
  'EmpirePortugal',
  // Victory
  'VictoryGlobalization',
  'VictoryHoly',
  'VictoryImperial',
  'VictoryRenaissance',
  // Tableau
  'PREN001_InquistionPope',
  'PREN002_PapalElephant',
  'PREN003_GrandInquisitor',
  'PREN004_Antipope',
  'PREN005_ReformedTheology',
  'PREN006_StarChamber',
  'PREN007_PetersPence',
  'PREN008_Jesuits',
  'PREN058_TheGrim',
  'PREN059_Safavids',
  'PREN060_Dervishes',
  'PREN061_Qizilbash',
  'PREN062_BarbarossaBrothers',
  'PREN063_OttomanNavy',
  'PREN064_JewishPirates',
  'PREN065_MamlukSlaveSoldiers',
  'PREN066_BlackArmy',
];
