<?php

namespace PaxRenaissance;

const OPTION_OPEN_HANDS = 100;
const OPTION_OPEN_HANDS_DISABLED = 0;
const OPTION_OPEN_HANDS_ENABLED = 1;

const OPTION_FIRST_PLAYER_VARIANT = 101;
const OPTION_FIRST_PLAYER_VARIANT_ENABLED = 1;
const OPTION_FIRST_PLAYER_VARIANT_DISABLED = 0;