<?php

namespace PaxRenaissance;

const OPTION_OPEN_HANDS = 100;
const OPTION_OPEN_HANDS_DISABLED = 0;
const OPTION_OPEN_HANDS_ENABLED = 1;

// NOTE: removed option. Do not reuse this id (101)
// const OPTION_FIRST_PLAYER_VARIANT = 101;
// const OPTION_FIRST_PLAYER_VARIANT_ENABLED = 1;
// const OPTION_FIRST_PLAYER_VARIANT_DISABLED = 0;

const OPTION_STARTING_MAP = 102;
const OPTION_STARTING_MAP_DEFAULT = 0;
const OPTION_STARTING_MAP_1550_VARIANT = 1;
const OPTION_STARTING_MAP_AGE_OF_REFORMATION_PROMO_VARIANT = 2;

const OPTION_ASTROLOGY_VARIANT = 103;
const OPTION_ASTROLOGY_VARIANT_DISABLED = 0;
const OPTION_ASTROLOGY_VARIANT_ENABLED = 1;

const OPTION_BANKRUPTCY_VARIANT = 104;
const OPTION_BANKRUPTCY_VARIANT_DISABLED = 0;
const OPTION_BANKRUPTCY_VARIANT_ENABLED = 1;

const OPTION_EXTENDED_GAME = 105;
const OPTION_EXTENDED_GAME_DISABLED = 0;
const OPTION_EXTENDED_GAME_ENABLED = 1;

const OPTION_LIMITED_CARD_SET = 106;
const OPTION_LIMITED_CARD_SET_DISABLED = 0;
const OPTION_LIMITED_CARD_SET_ENABLED = 1;

const OPTION_STRAWMAN_CAMPAIGN = 107;
const OPTION_STRAWMAN_CAMPAIGN_DISABLED = 0;
const OPTION_STRAWMAN_CAMPAIGN_ENABLED = 1;



